#!/usr/bin/env bash

# Install ansible
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible

# Pull ansible
sudo ansible-pull -U https://github.com/bytefl0w/ansible.git
