#!/usr/bin/env bash

sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible git

# Clone ansible repo from github
git clone https://github.com/bytefl0w/ansible
cd ansible && sudo ./ansible-run
